### ISSUE TITLE
Unable to use podRentInterruptable

### ISSUE THREAD

**Issue by nbanks** [runpod/runpodctl#11]
Using [the web interface](https://www.runpod.io/console/gpu-cloud) I'm able to Deploy a spot Instance instead of an On Demand instance.  It would be nice to be able to do this using the command line tool too.

I tried naively replacing podFindAndDeployOnDemand with podRentInterruptable, but this failed.  I have no idea if this was a permission problem, a server problem, or a client problem.  (If I could get it to work, I'd provide a pull request.)  I can see the current spot price using `runpodctl get cloud`.  Once I create a pod through the web, I am able to see it and stop it using the command line interface.  
[I found this documentation.](https://graphql-spec.runpod.io/#mutation-podRentInterruptable)

**Comment by zhl146** [comment]
You can do this via the gql api: https://docs.runpod.io/graphql-api/create-pod#create-spot-pod

This was never added to the cli, though. Feel free to add it via PR an we'll add it eventually!
