### ISSUE TITLE
Fix Windows install URL in Readme

### ISSUE THREAD

**Issue by ingmarsell** [runpod/runpodctl#132]
# Fix Windows install URL in Readme

The Windows install URL in the Readme is outdated and no longer works

`wget https://github.com/runpod/runpodctl/releases/download/v1.9.0/runpodctl-windows-amd64.exe -O runpodctl.exe`
Needs to be updated to
`wget https://github.com/runpod/runpodctl/releases/download/v1.14.2/runpodctl-windows-amd64.exe -O runpodctl.exe`

**Comment by Rokkonrol** [comment]
Thanks, this was driving me crazy trying to figure out the issue.

**Comment by DireLines** [comment]
will do, thanks for the reminder. Will update it and also see if github maintains a "latest build" url

**Comment by DireLines** [comment]
https://github.com/runpod/runpodctl/pull/135
