### ISSUE TITLE
Create CPU Pod using runpodctl

### ISSUE THREAD

**Issue by pfk-beta** [runpod/runpodctl#133]
Hello,

I would like to create non-gpu Pod for quick experimenting, before running GPU Pod. I cannot create CPU Pod, because runpodctl requires gpuType.

**Comment by DireLines** [comment]
we recently added CPU pods as a feature and didn't make the change in runpodctl yet, working on this now

**Comment by pfk-beta** [comment]
not urgen, not important. Just mentioning. I think if you are aware of it, I can close the issue :)
