### ISSUE TITLE
Get ssh parameters using runpodctl

### ISSUE THREAD

**Issue by pfk-beta** [runpod/runpodctl#134]
is there a way to obtain hostname and port of Pod's ssh using runpodctl? I would like to automate benchmarking my models, but I need to automate ssh connection.

**Comment by justinmerrell** [comment]
Would you be able to provide some additional information as to what you are looking to do specifically and how you will be automating your SSH connections? 

Typically you would use graphql to get both the pods hostname and port. Are you using the public IP to access a pod? Query the pod (https://graphql-spec.runpod.io/#query-pod), returning the public IP, and runtime info which will contain the port pairs, you would use the public port that is paired with the internal port 22.
