### ISSUE TITLE
does this thing even work?

### ISSUE THREAD

**Issue by jtoy** [runpod/runpodctl#15]
every single call to both the api and using runpodctl ends with errors like:
context deadline exceeded (Client.Timeout exceeded while awaiting headers)

**Comment by zhl146** [comment]
Hey, sorry. I didn't see this earlier. Yes, we have many users using this. Are you trying to use it from your local or from within a pod?

If you can provide more details, it would help us debug a bit more.

**Comment by src-r-r** [comment]
I'm experiencing this, so I'd like to reopen this issue. I'm on a local machine trying to connect to a pod.

**Comment by src-r-r** [comment]
I think it's because I'm behind a VPN. Changed the timeout to 10 seconds and the request completed. Fixed it with https://github.com/runpod/runpodctl/pull/33

**Comment by zhl146** [comment]
Ah that makes sense. Thanks for following up on it!
