### ISSUE TITLE
Could not create pod with networkVolume using CLI

### ISSUE THREAD

**Issue by vanduc2514** [runpod/runpodctl#172]
I run this command to create an ollama pod with network volume

```bash
runpodctl create pod \
    --name test-ollama \
    --imageName ollama/ollama \
    --ports '11434/http' \
    --networkVolumeId test-volume \
    --volumePath "/root/.ollama" \
    --secureCloud \
    --gpuCount 1 \
    --gpuType 'NVIDIA GeForce RTX 4090'
```

Network Volume in EU-RO-1 region

The pod could not be created and console shows this message 

`Error: Something went wrong. Please try again later or contact support.`

**Note:** Pod can be created via Runpod.io Web UI

**Comment by jiminshi** [comment]
Which region did you change to? Can't seem to resolve mine. I first created mine at EU-SE-1 and then tried CA but still got the enigmatic error message.

**Comment by WaywardWizard** [comment]
There is a note that says network volumes are only available in secure cloud. Its necessary to use the --secureCloud flag. Then it works.
