### ISSUE TITLE
It won't finish sending and/or receiving 

### ISSUE THREAD

**Issue by roperi** [runpod/runpodctl#19]
Using runpodctl v1.8.0. 

I have been trying to send a 172MB file in the last hour without any success. I keep retrying to no avail.

Sometimes when I send it will just stop in the middle of the job, and it stays like that, like frozen.  
```
$ runpodctl send samples.zip                         
Sending 'samples.zip' (172.4 MB) 
Code is: 1100-yahoo-boat-friend-0
On the other computer run

runpodctl receive 1100-yahoo-boat-friend-0

Sending (->XX.XX.XXX:40806)
samples.zip  90% |██████████████████  | (156/172 MB, 478.021 kB/s) [3m42s:34s]
```
... so it never finishing downloading at my end. 

But then there's another problem, when the sending actually completes with 100%, my receiving end (say my PC) will stop receiving in the middle of it. Again, like frozen. It's like a communication breakdown and thing doesn't know what to do next so it stays in a frozen state.

**Comment by zhl146** [comment]
We'll have to see if we can reproduce this. Thanks for the report! @ps0296

**Comment by roperi** [comment]
@zhl146

I finally managed to transfer it. It looked like there was some problems with the connection. In general it was freezing towards 100%, but never before 70% completion.

**Comment by zhl146** [comment]
Yeah, it could definitely be an issue with your local connection, but it's hard to say. I think there's a verbose flag that may give you more information. Can you reproduce it when you transfer to/from other places?

**Comment by roperi** [comment]
>  Can you reproduce it when you transfer to/from other places?

Sure. I'll do that next time it happens. Thanks.

**Comment by roperi** [comment]
It happened again. 30 minutes and about a dozen attempts just to upload one  8MB zip file to a runpod. 

Is there a way to add a verbose flag?

**Comment by zhl146** [comment]
not currently - we upgraded all of our relays to be 20x faster so you should see less of this!

**Comment by JaniceLC** [comment]
It happened to me as well. I am trying to upload my dataset. It is frozen when it approaches 90% ... and it spends 4 hours and clashes... This happened twice today. Thus, I cannot run on runpod at all.
