### ISSUE TITLE
Is there any way to pass in an argument to the pod with this

### ISSUE THREAD

**Issue by xenotropic** [runpod/runpodctl#21]
When I'm doing `runpodctl start pod {podId}` is there any way to pass in a command argument to the pod? Like send the docker command, or something that would be appended to the docker command, or set a bash environment variable, any other way I can pass an argument string to the pod from my remote command line where I'm invoking runpodctl? My goal here is to be able to start a pod remotely and point it at a target URL that it should process. I know I can set a startup docker command from within the web interface, but I'm hoping to be able to do something like that from the command line.

**Comment by zhl146** [comment]
https://github.com/runpod/runpodctl/blob/main/doc/runpodctl_create_pod.md
