### ISSUE TITLE
Show pod IP for get pod cmd

### ISSUE THREAD

**Issue by rougsig** [runpod/runpodctl#39]
Looks like [graphql](https://graphql-spec.runpod.io/#definition-PodRuntime) spec can return information about pod ip.

I wanna to create pod with ctl and then connect with ssh to created pod.

**Comment by pw-git** [comment]
I added a PR for this, see above. Please note that depending on factors unknown to me, it might take a while until the IPs and port mapping are available on graphql. So calling `runpodctl get pod` immediately after creating a new pod will sometimes not contain the IPs and ports.
During my tests is seemed to me that for "community" servers it took a bit longer than for the "secure" ones.
