### ISSUE TITLE
Please add binaries for linux and android on arm

### ISSUE THREAD

**Issue by Efreak** [runpod/runpodctl#51]
This should be as simple as setting goarch=arm and arm64 and goos=android and linux, but my fork failed to build for some reason.I'm not familiar with this release please, that might be part of it?

**Comment by DireLines** [comment]
it is as simple as that, I'll add those architectures to the next release, you are heard

**Comment by DireLines** [comment]
for now if you clone locally and run `make` it should hopefully build for your local system

**Comment by Efreak** [comment]
> for now if you clone locally and run make it should hopefully build for your local system

Unfortunately, golang build process is using features (flock syscall, iirc) that aren't implemented in Android, so I can't. Termux allows you to download and install golang from the repo, but it's not actually usable on the majority of devices 🙄

**Comment by DireLines** [comment]
added in latest release, let me know if they don't work as expected
